steps:
  - label: "🤡 :hammer:"
    plugins:
      - docker-compose#v3.3.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - docker-compose#v3.3.0:
          run: lint
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.1.2:
          files: hooks/**
